# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: codemode.rocks
email: fyrkant@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Codemode is a selection of tips from one newbie programmer to other newbie programmers.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codemode.rocks" # the base hostname & protocol for your site
twitter_username: bultbrada
github_username:  mw222rs

# Build settings
markdown: kramdown
